///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetBookOfferData {
/*
{
  "book_id": "14",
  "book_name": "Word find Puzzles with Inspirational Bible Verses",
  "storeTitle": "Amazon",
  "book_url": "https://www.amazon.com/BIBLE-VERSE-Search-WOMEN-Words/dp/B0BRDFRXS5/ref=sxin_16_pa_sp_search_thematic_sspa?content-id=amzn1.sym.fd6a1933-d63f-4f89-91aa-2edceaf8d1e3:amzn1.sym.fd6a1933-d63f-4f89-91aa-2edceaf8d1e3&crid=1Q9GIMN2CDRFK&cv_ct_cx=english+bible+c",
  "book_published_by": "Peter Burch",
  "book_description": "This is a perfect gift for Moms, Grandmas, or anyone you love who enjoys solving puzzles.\r\nNourish your spirit by exercising your brain.\r\nLearn God's Word through 101 biblical puzzles.",
  "book_age": "50",
  "bookThumbURL": "https://saveigm.com/bookads/admin/uploads/books/bo_1718094642348281.jpg"
} 
*/

  String? bookId;
  String? bookName;
  String? storeTitle;
  String? bookUrl;
  String? bookPublishedBy;
  String? bookDescription;
  String? bookAge;
  String? bookThumbURL;

  GetBookOfferData({
    this.bookId,
    this.bookName,
    this.storeTitle,
    this.bookUrl,
    this.bookPublishedBy,
    this.bookDescription,
    this.bookAge,
    this.bookThumbURL,
  });
  GetBookOfferData.fromJson(Map<String, dynamic> json) {
    bookId = json['book_id']?.toString();
    bookName = json['book_name']?.toString();
    storeTitle = json['storeTitle']?.toString();
    bookUrl = json['book_url']?.toString();
    bookPublishedBy = json['book_published_by']?.toString();
    bookDescription = json['book_description']?.toString();
    bookAge = json['book_age']?.toString();
    bookThumbURL = json['bookThumbURL']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['book_id'] = bookId;
    data['book_name'] = bookName;
    data['storeTitle'] = storeTitle;
    data['book_url'] = bookUrl;
    data['book_published_by'] = bookPublishedBy;
    data['book_description'] = bookDescription;
    data['book_age'] = bookAge;
    data['bookThumbURL'] = bookThumbURL;
    return data;
  }
}

class GetBookOffer {
/*
{
  "result": "1",
  "msg": "success",
  "data": [
    {
      "book_id": "14",
      "book_name": "Word find Puzzles with Inspirational Bible Verses",
      "storeTitle": "Amazon",
      "book_url": "https://www.amazon.com/BIBLE-VERSE-Search-WOMEN-Words/dp/B0BRDFRXS5/ref=sxin_16_pa_sp_search_thematic_sspa?content-id=amzn1.sym.fd6a1933-d63f-4f89-91aa-2edceaf8d1e3:amzn1.sym.fd6a1933-d63f-4f89-91aa-2edceaf8d1e3&crid=1Q9GIMN2CDRFK&cv_ct_cx=english+bible+c",
      "book_published_by": "Peter Burch",
      "book_description": "This is a perfect gift for Moms, Grandmas, or anyone you love who enjoys solving puzzles.\r\nNourish your spirit by exercising your brain.\r\nLearn God's Word through 101 biblical puzzles.",
      "book_age": "50",
      "bookThumbURL": "https://saveigm.com/bookads/admin/uploads/books/bo_1718094642348281.jpg"
    }
  ]
} 
*/

  String? result;
  String? msg;
  List<GetBookOfferData?>? data;

  GetBookOffer({
    this.result,
    this.msg,
    this.data,
  });
  GetBookOffer.fromJson(Map<String, dynamic> json) {
    result = json['result']?.toString();
    msg = json['msg']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <GetBookOfferData>[];
      v.forEach((v) {
        arr0.add(GetBookOfferData.fromJson(v));
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['result'] = result;
    data['msg'] = msg;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
