///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RegisterDataUser {
/*
{
  "name": "testuser1",
  "email": "testuser1@test.com",
  "user_id": "eyJpdiI6IlR0V2lyb0tuajF1QTdpSjgwZ0NTYVE9PSIsInZhbHVlIjoiMnFSTVVUajMwbGlaTkFTQUdMT01JQT09IiwibWFjIjoiNWM1MTBlNDQzMzk3NzFlZTAxMjY5ZDJhNTBiZmUyZjBjYTA0NjU2NTIxY2I2N2UwZjhjNDRiNWUxYTk3YTlkYyIsInRhZyI6IiJ9",
  "app_id": "d15e5a03-d755-11ef-ae3c-fa163e8c011b"
} 
*/

  String? name;
  String? email;
  String? userId;
  String? appId;

  RegisterDataUser({
    this.name,
    this.email,
    this.userId,
    this.appId,
  });
  RegisterDataUser.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    email = json['email']?.toString();
    userId = json['user_id']?.toString();
    appId = json['app_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['email'] = email;
    data['user_id'] = userId;
    data['app_id'] = appId;
    return data;
  }
}

class RegisterData {
/*
{
  "user": {
    "name": "testuser1",
    "email": "testuser1@test.com",
    "user_id": "eyJpdiI6IlR0V2lyb0tuajF1QTdpSjgwZ0NTYVE9PSIsInZhbHVlIjoiMnFSTVVUajMwbGlaTkFTQUdMT01JQT09IiwibWFjIjoiNWM1MTBlNDQzMzk3NzFlZTAxMjY5ZDJhNTBiZmUyZjBjYTA0NjU2NTIxY2I2N2UwZjhjNDRiNWUxYTk3YTlkYyIsInRhZyI6IiJ9",
    "app_id": "d15e5a03-d755-11ef-ae3c-fa163e8c011b"
  },
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5ZTAzZTg3OS02MmQyLTRmYWYtYTRjYS1hMmE4ZjQ1MGJlZGYiLCJqdGkiOiJmYjQ4ZDJlM2M3YTQ2OWU3NzgwMTBiYzRkZDUwOGRhNGU3NWY1ZGQxZWVmMjQ0NjgwODEwYjc1MmI4ZmQ5NjBjNTUwZWEwZjhlNDJjNGFmNSIsImlhdCI6MTczODc1OTkxNy44MTg5MjQ5MDM4Njk2Mjg5MDYyNSwibmJmIjoxNzM4NzU5OTE3LjgxODkyNzA0OTYzNjg0MDgyMDMxMjUsImV4cCI6MTc0MTM1MTkxNy44MTE0MDIwODI0NDMyMzczMDQ2ODc1LCJzdWIiOiI3Iiwic2NvcGVzIjpbXX0.lr2SUxlSG-fwYwUhEsLoFseEd4Gh16bvmeEXNEdqqO87M1XU8l9LzJg1amBGcWNpNHVAYrrF-_c6AkAaS8rff6BpfFJdWlUTdTmzACADq-v4RvC9Al6omgG6IAh1IyajlQXi2aNWNl39dvuN4QpJlFMXZNlhdXgii7d9ZgQld4PwHZHKwZtmYdFIS9J-D3elmKclTiFFOkYhiINO-smmxnNc6eoY3qlB0Hm0TWc66xk15FBpn4HjeLZV6APGH9SBmd7EKLRasG71dI3gNN3NK_W26eYny_Z2JaY7Tey0Z9lyqrY9-CgYtU406YyTewf_d6WYVwH6y1g7SCuh4y6cEVEoQrx6dXfhZeOJi7pM6zzkv9Oi0XwJN-GYfobf1Pd1sKUMTmJlMTbuyL8bwV6CAjtCI5zwTKR5Z-bYeTOiBu64CA3JmiSuQspJO72uQmarQG9Vu3rF1ohg1OowEBfsxs94BbqaKEcRQsNZolmilHCar6cFRwTcz3oxn_wEhVjpFgCX-gqOSVs73W83RKutLGeBeEGhA6UIoOBfvLzkB2A32-bepxhE_YZzbPPby27cvakCtfS51ChDqNF5G5dpoyg9_YdJllu6J3CL8E543vmxnCElJsUrhXZMc-KESuHop3G5FIkjE8vG2FjlTlF-cMhbWTLuiGi9_RXT-Ptm4MU"
} 
*/

  RegisterDataUser? user;
  String? token;

  RegisterData({
    this.user,
    this.token,
  });
  RegisterData.fromJson(Map<String, dynamic> json) {
    user =
        (json['user'] != null) ? RegisterDataUser.fromJson(json['user']) : null;
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['token'] = token;
    return data;
  }
}

class Register {
/*
{
  "status": true,
  "status_code": 200,
  "message": "Successfully Registered",
  "data": {
    "user": {
      "name": "testuser1",
      "email": "testuser1@test.com",
      "user_id": "eyJpdiI6IlR0V2lyb0tuajF1QTdpSjgwZ0NTYVE9PSIsInZhbHVlIjoiMnFSTVVUajMwbGlaTkFTQUdMT01JQT09IiwibWFjIjoiNWM1MTBlNDQzMzk3NzFlZTAxMjY5ZDJhNTBiZmUyZjBjYTA0NjU2NTIxY2I2N2UwZjhjNDRiNWUxYTk3YTlkYyIsInRhZyI6IiJ9",
      "app_id": "d15e5a03-d755-11ef-ae3c-fa163e8c011b"
    },
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5ZTAzZTg3OS02MmQyLTRmYWYtYTRjYS1hMmE4ZjQ1MGJlZGYiLCJqdGkiOiJmYjQ4ZDJlM2M3YTQ2OWU3NzgwMTBiYzRkZDUwOGRhNGU3NWY1ZGQxZWVmMjQ0NjgwODEwYjc1MmI4ZmQ5NjBjNTUwZWEwZjhlNDJjNGFmNSIsImlhdCI6MTczODc1OTkxNy44MTg5MjQ5MDM4Njk2Mjg5MDYyNSwibmJmIjoxNzM4NzU5OTE3LjgxODkyNzA0OTYzNjg0MDgyMDMxMjUsImV4cCI6MTc0MTM1MTkxNy44MTE0MDIwODI0NDMyMzczMDQ2ODc1LCJzdWIiOiI3Iiwic2NvcGVzIjpbXX0.lr2SUxlSG-fwYwUhEsLoFseEd4Gh16bvmeEXNEdqqO87M1XU8l9LzJg1amBGcWNpNHVAYrrF-_c6AkAaS8rff6BpfFJdWlUTdTmzACADq-v4RvC9Al6omgG6IAh1IyajlQXi2aNWNl39dvuN4QpJlFMXZNlhdXgii7d9ZgQld4PwHZHKwZtmYdFIS9J-D3elmKclTiFFOkYhiINO-smmxnNc6eoY3qlB0Hm0TWc66xk15FBpn4HjeLZV6APGH9SBmd7EKLRasG71dI3gNN3NK_W26eYny_Z2JaY7Tey0Z9lyqrY9-CgYtU406YyTewf_d6WYVwH6y1g7SCuh4y6cEVEoQrx6dXfhZeOJi7pM6zzkv9Oi0XwJN-GYfobf1Pd1sKUMTmJlMTbuyL8bwV6CAjtCI5zwTKR5Z-bYeTOiBu64CA3JmiSuQspJO72uQmarQG9Vu3rF1ohg1OowEBfsxs94BbqaKEcRQsNZolmilHCar6cFRwTcz3oxn_wEhVjpFgCX-gqOSVs73W83RKutLGeBeEGhA6UIoOBfvLzkB2A32-bepxhE_YZzbPPby27cvakCtfS51ChDqNF5G5dpoyg9_YdJllu6J3CL8E543vmxnCElJsUrhXZMc-KESuHop3G5FIkjE8vG2FjlTlF-cMhbWTLuiGi9_RXT-Ptm4MU"
  }
} 
*/

  bool? status;
  int? statusCode;
  String? message;
  RegisterData? data;

  Register({
    this.status,
    this.statusCode,
    this.message,
    this.data,
  });
  Register.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    statusCode = json['status_code']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? RegisterData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['status_code'] = statusCode;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
