///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TemptokenData {
/*
{
  "temp_access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5ZTAzZTVmMS02MjFiLTQyMmMtOGRiOS0zMDc3OGU2NzQzODYiLCJqdGkiOiIzZTQzZWEwNjI0OGJhYWZiYmRkNjkwMDBmYmYzMzE4OWYyMDU5ZWU1NzAwOWUwNjhmZmY0NDVkMTYzODJiMGUzNDEyMGNlMGRiNmFiMjZkZCIsImlhdCI6MTczODc1NDE0OS4zNTUyNTc5ODc5NzYwNzQyMTg3NSwibmJmIjoxNzM4NzU0MTQ5LjM1NTI1OTg5NTMyNDcwNzAzMTI1LCJleHAiOjE3NDEzNDYxNDkuMzUyMDgyOTY3NzU4MTc4NzEwOTM3NSwic3ViIjoiIiwic2NvcGVzIjpbXX0.rWVWCOQqyHk3iiIBZfoprpPbelJa2mUFfh0AlCGYxsRYZPp-DgwwZ2V8fK8dqprwIhyjL3IQgss6KJ-M0Syj0NfqSkxPt57A3zADod3sA_KbOlUAs2B8XG0R7ZYYGGRJi1Ni1GfRL5uQg862e3QQMJ4mhVnPu_ZzmzpMAv5pITaqx8RehQc6Tw2d6p2bkh9Wq9Nek752ejbVMOo0w5dOiOO9FHCgJBb1tCRyAEL_ip83Cvkv-SXzUPpaEt-PvLIDYzJJTP2gCgfyOyhpJOoItsjpztdUJF2wV5fP7H5GdHzutSG0f9jHtGiohDKCDKDV2GTH77r0D54pF3n5otbK_ZmK9dCpdh9ngidxgs723tqFfoiZPLym7EjlnnjtA5YWYClPisluty84o7DCbWqVf7ILxyLxjcdDbCmyP2MKAOLYcZMcunW3634g1_QP6INIrkHVmziffg-QlY5OALRqAFOcdM6OCjmVBk1DWkl7cvnPtjmUZwTh_ymCqdbG1loZSQqxl7pbvFEV0YJCzTqwtALM1fRhxraCRi8TWunj8sXkgAwAdXFQf4aNqqMRWg8M490Dhq0SPCtYUpIVsBA0G2fiRL5ykbP_IwW3SPU_TBmYBgFGRcLErtC3a4b3oYdohmJHfj8X9OhayoZRPbA9VfAP9wu6LcxnpOasDcr5E0U",
  "expires_in": 900
} 
*/

  String? tempAccessToken;
  int? expiresIn;

  TemptokenData({
    this.tempAccessToken,
    this.expiresIn,
  });
  TemptokenData.fromJson(Map<String, dynamic> json) {
    tempAccessToken = json['temp_access_token']?.toString();
    expiresIn = json['expires_in']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['temp_access_token'] = tempAccessToken;
    data['expires_in'] = expiresIn;
    return data;
  }
}

class Temptoken {
/*
{
  "status": true,
  "status_code": 200,
  "message": "success",
  "data": {
    "temp_access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5ZTAzZTVmMS02MjFiLTQyMmMtOGRiOS0zMDc3OGU2NzQzODYiLCJqdGkiOiIzZTQzZWEwNjI0OGJhYWZiYmRkNjkwMDBmYmYzMzE4OWYyMDU5ZWU1NzAwOWUwNjhmZmY0NDVkMTYzODJiMGUzNDEyMGNlMGRiNmFiMjZkZCIsImlhdCI6MTczODc1NDE0OS4zNTUyNTc5ODc5NzYwNzQyMTg3NSwibmJmIjoxNzM4NzU0MTQ5LjM1NTI1OTg5NTMyNDcwNzAzMTI1LCJleHAiOjE3NDEzNDYxNDkuMzUyMDgyOTY3NzU4MTc4NzEwOTM3NSwic3ViIjoiIiwic2NvcGVzIjpbXX0.rWVWCOQqyHk3iiIBZfoprpPbelJa2mUFfh0AlCGYxsRYZPp-DgwwZ2V8fK8dqprwIhyjL3IQgss6KJ-M0Syj0NfqSkxPt57A3zADod3sA_KbOlUAs2B8XG0R7ZYYGGRJi1Ni1GfRL5uQg862e3QQMJ4mhVnPu_ZzmzpMAv5pITaqx8RehQc6Tw2d6p2bkh9Wq9Nek752ejbVMOo0w5dOiOO9FHCgJBb1tCRyAEL_ip83Cvkv-SXzUPpaEt-PvLIDYzJJTP2gCgfyOyhpJOoItsjpztdUJF2wV5fP7H5GdHzutSG0f9jHtGiohDKCDKDV2GTH77r0D54pF3n5otbK_ZmK9dCpdh9ngidxgs723tqFfoiZPLym7EjlnnjtA5YWYClPisluty84o7DCbWqVf7ILxyLxjcdDbCmyP2MKAOLYcZMcunW3634g1_QP6INIrkHVmziffg-QlY5OALRqAFOcdM6OCjmVBk1DWkl7cvnPtjmUZwTh_ymCqdbG1loZSQqxl7pbvFEV0YJCzTqwtALM1fRhxraCRi8TWunj8sXkgAwAdXFQf4aNqqMRWg8M490Dhq0SPCtYUpIVsBA0G2fiRL5ykbP_IwW3SPU_TBmYBgFGRcLErtC3a4b3oYdohmJHfj8X9OhayoZRPbA9VfAP9wu6LcxnpOasDcr5E0U",
    "expires_in": 900
  }
} 
*/

  bool? status;
  int? statusCode;
  String? message;
  TemptokenData? data;

  Temptoken({
    this.status,
    this.statusCode,
    this.message,
    this.data,
  });
  Temptoken.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    statusCode = json['status_code']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? TemptokenData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['status_code'] = statusCode;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
